name: Mirror to JihuLab

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  mirror-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH for JihuLab
      env:
        SSH_PRIVATE_KEY: ${{ secrets.JIHULAB_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo -e "Host jihulab.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        
    - name: Create Bare Mirror Repository
      run: |
        # 创建临时目录
        TEMP_DIR=$(mktemp -d)
        echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV
        
        # 克隆GitHub仓库的裸镜像
        echo "正在创建裸镜像仓库..."
        git clone --bare https://github.com/xkk1/xkk1.github.io.git $TEMP_DIR
        echo "裸镜像仓库创建完成！"
        
    - name: Push Mirror to JihuLab
      run: |
        echo "正在将裸镜像推送到 JihuLab..."
        cd ${{ env.TEMP_DIR }}
        
        # 添加 JihuLab 远程仓库
        git remote add jihulab git@jihulab.com:xkk1/xkk1.jihulab.io.git
        
        # 推送完整镜像到 JihuLab
        git push --mirror jihulab
        echo "镜像推送成功！"
        
    - name: Cleanup Temporary Directory
      run: |
        echo "正在清理临时目录..."
        rm -rf ${{ env.TEMP_DIR }}
        echo "清理完成！"
